### ISSUE TITLE
Pointer vanishes over window

### ISSUE THREAD

**Issue by jgharston** [stardot/MatrixBrandy#20]
The pointer vanishes when you move it over the output window. Rather disconcerting!

**Comment by soruk42** [comment]
As on RISC OS, when you select a screen mode the mouse is off by default. Type MOUSE ON to display the pointer.

**Comment by soruk42** [comment]
While not enabled by default as this contradicts RISC OS behaviour, I've added a compile time option (add -DSHOWMOUSE to makefile) that causes the mouse pointer to be displayed on startup and mode change.

**Comment by jgharston** [comment]
Michael McConnell wrote:
> As on RISC OS, when you select a screen mode the mouse is off by
> default. Type MOUSE ON to display the pointer.

But I haven't selected a screen mode, I've started a windowed
multi-tasking instance of Basic, in a multitasking windowed
environment, and the pointer should be visible, see:
http://mdfs.net/temp/pointer.gif

If in a full-screen mode, then yes, the pointer should by default
be invisible, but it is not in a full-screen mode.

Plus, it's damn confusing not knowing where the pointer is.

-- 
J.G.Harston - jgh@mdfs.net - mdfs.net/jgh

**Comment by soruk42** [comment]
While I disagree with the premise of not having selected a screen mode - it selects a mode on startup (specifically, mode 0), akin to an Archimedes or RPC starting when configured to boot ito BASIC rather than the desktop, it selects the mode set in *CONFIGURE MODE - I get that it is confusing to lose the pointer over the window.

(Task Window isn't an accurate comparison, you can't change mode or do graphics in it)

I've pushed a change to mainline that defaults the mouse to ON upon startup or mode change when windowed, and OFF when fullscreen.

**Comment by jgharston** [comment]
Thanks for that, I'll grab the updates.
(Bit fiddly ATM as Git won't let me up/download anything from my programming PC, I have to do everything from my laptop.)

**Comment by jgharston** [comment]
Works nicely now, issue can be closed.
